/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMyBarForm: typeof import('./src/components/Bar/AddMyBarForm.vue')['default']
    BarFilterButtons: typeof import('./src/components/Bar/BarFilterButtons.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    FilterButtons: typeof import('./src/components/Cocktails/FilterButtons.vue')['default']
    FilterFields: typeof import('./src/components/Cocktails/FilterFields.vue')['default']
    InputText: typeof import('./src/components/Fields/InputText.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareBar: typeof import('./src/components/UserSettings/ShareBar.vue')['default']
    Statistic: typeof import('./src/components/UserSettings/Statistic.vue')['default']
    TheBar: typeof import('./src/components/Bar/TheBar.vue')['default']
    TheCocktail: typeof import('./src/components/Cocktails/TheCocktail.vue')['default']
    TheFilter: typeof import('./src/components/TheFilter.vue')['default']
    TheFinder: typeof import('./src/components/Cocktails/TheFinder.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLoader: typeof import('./src/components/TheLoader.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TheSettings: typeof import('./src/components/UserSettings/TheSettings.vue')['default']
    TheStats: typeof import('./src/components/UserSettings/TheStats.vue')['default']
    UserPage: typeof import('./src/components/UserSettings/UserPage.vue')['default']
  }
}
